build = "build.rs"

[package]
edition = "2021"
authors = ["Manuel Sopena Ballesteros <msopena@cscs.ch>"]
name = "mesa"
description = "A library for Shasta"
version = "0.35.3"
license-file = "LICENSE"
documentation = "https://github.com/eth-cscs/mesa/blob/main/README.md"
homepage = "https://github.com/eth-cscs/mesa/blob/main/README.md"
repository = "https://github.com/eth-cscs/mesa"
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.25.0"
strum_macros = "0.25"
chrono = "0.4.31"
anyhow = "1.0.44"
thiserror = "1.0.56"
reqwest = { version = "0.11", features = ["blocking", "json", "rustls-tls", "socks"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.17"
log = "0.4.17"
# env_logger = "0.9.0" # Changing to log4rs because we also need to log in files for auditing
log4rs = "1.2.0" # Docs about pattern encoder https://docs.rs/log4rs/0.10.0/log4rs/encode/pattern/index.html
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.24.0" # used by kube-rs to configure client with socks proxy -- REMOVE
# tokio-native-tls = "0.3.0" # used by kube-rs to configure client with socks proxy -- REMOVE
tokio-util = "0.7.4"       # used by manta_console to create a read stream from container stdout
tokio-stream = "0.1.11"    # used by manta_console to create a read stream from container stdout (alternative?)
kube = { version = "0.85.0", features = ["kube-client", "kube-runtime", "derive", "rustls-tls", "ws"] }
k8s-openapi = { version = "0.19.0", features = ["v1_26"] }
rustls-pemfile = "1.0.3"
# https://github.com/kube-rs/kube-rs/discussions/1012 and https://crates.io/crates/hyper-socks2
hyper-socks2 = { version = "0.8.0", default-features = false, features = ["rustls"] } # needed by kube-rs (to operate with kube api) 
hyper = { version = "0.14", features = ["full"] } # needed by kube-rs (to operate with kube api)
hyper-rustls = { version = "0.24.0", features = ["webpki-roots"] } # used by kube-rs to configure client with socks proxy
# hyper-tls = "0.5.0" # needed by kube-rs (to operate with kube api) -- REMOVE ???
tower = "0.4.13"
# native-tls = "0.2.10"
# rustls = { version = "0.21.1", features = [ "dangerous_configuration" ] }
futures = "0.3.28" 
# futures-util = "0.3.24"
clap = { version =  "4.0.32", features = ["derive","cargo"] }
clap_complete = "4.0.3"
git2 = "0.18.1"
# walkdir = "2.3.2"
dialoguer = "0.10.2"
substring = "1.4.5"
regex = "1.6.0"
directories = "4.0.1" # XDG Base Directory Specification
config = { version = "0.13.2", features = ["toml"] } # used to read manta configuration file
secrecy = "0.8.0"
# openssl-sys = { version = "0.9.87", features = ["vendored"] }
# bytes = { version = "1", features = ["serde"] }
termion = "2.0.1" # used by manta_console to enable terminal raw
dhat = "0.3.2"
base64 = "0.13.1"
jsonwebtoken = "8.3.0"
aws-sdk-s3 = "1.12.0" # used to download IMS images from S3 endpoint
aws-config = "1.1.2" # used to configure the http connector to s3 endpoint with socks5 and CSM CA root
aws-smithy-runtime = { version = "1.0.1" }
aws-smithy-runtime-api = { version = "1.0.1", features = ["client"] }
aws-smithy-client = { version = "0.60.3" }
aws-smithy-types = { version = "1.1.2", features = ["rt-tokio", "http-body-0-4-x"] }
humansize = "2.0.0"
indicatif = "0.17.7"

mime_guess = "2"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
rand = "0.8.5"
tempfile = "3.8.1"
uuid = "1.6.1"
# aws-smithy-runtime-api = "0.56.1"
# aws-smithy-runtime = "0.56.1"

[build-dependencies]
clap = "4.0.32"
clap_complete = "4.0.3"

[profile.release]
opt-level = "s" # Tell `rustc` to optimize for small code size.
#incremental = true
debug = 1

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.7"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.67.1"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# The installers to generate for each app
installers = []
# Whether to consider the binaries in a package for distribution (defaults true)
dist = true

#[features]
#dhat-heap = []    # if you are doing heap profiling
#dhat-ad-hoc = []  # if you are doing ad hoc profiling
